galaxy_info:
  author: amirex
  description: Deploy and configure Vim with plugins
  company: frotel

  license: MIT

  min_ansible_version: 2.8

  platforms:
  - name: ubuntu
    versions:
    - 20.4

  galaxy_tags: []

dependencies: []